In [1]:
import numpy as np

In [23]:
def gradient(u, v):
    temp_u = np.exp(u) + v*np.exp(u*v) + 2*u - 2*v -3
    temp_v = 2 * np.exp(2*v) + u*np.exp(u*v) - 2*u + 4*v - 2
    return (temp_u, temp_v)

In [24]:
u = 0
v = 0
for i in range(5):
    result = gradient(u, v)
    u -= 0.01*result[0]
    v -= 0.01*result[1]

In [25]:
Euv = np.exp(u) + np.exp(2*v) + np.exp(u*v) + u*u -2*u*v + 2*v*v -3*u -2*v
Euv

2.8250003566832635

In [39]:
def newtonGradient(u,v):
    dudv = -1
    dudu = 3
    dvdu = -1
    dvdv = 8
    hessian = np.mat([[dudv,dudu],[dvdu,dvdv]])
    du = 3*u - v -2
    dv = 8*v -u
    deltaE = [du,dv]
    result = np.dot(hessian.I, deltaE)
    return result

In [40]:
u = 0
v = 0
for i in range(5):
    result = newtonGradient(u, v)
    print(result)
    u += 0.01* result[0,0]
    v += 0.01* result[0,1]

[[3.2 0.4]]
[[3.0528 0.3816]]
[[2.9123712 0.3640464]]
[[2.77840212 0.34730027]]
[[2.65059563 0.33132445]]


In [41]:
Euv = np.exp(u) + np.exp(2*v) + np.exp(u*v) + u*u -2*u*v + 2*v*v -3*u -2*v
Euv

2.7392831519406657

In [42]:
def generateData():
    X = np.random.uniform(-1,1,size=(1000,2))
    Y = np.array([[np.sign(x[0]*x[0] + x[1]*x[1] -0.6)] for x in X])
    noise_index = np.random.choice(len(Y),int(len(Y)* 0.1))
    Y[noise_index] *= -1
    return (X, Y)

In [75]:
def linear_regression(data, label):
    data = np.insert(data, 0, values=1, axis=1)
    temp = np.mat(np.dot(data.T, data))
    hessian = np.dot(temp.I, data.T)
    w = np.dot(hessian,label)
    return w

In [83]:
def compute_linear_regression_error(X, Y, w):
    y_temp = np.dot(X,w)
    resultY = np.sign(y_temp)
    return (Y!=resultY).sum()/len(Y)

In [84]:
err = 0
for i in range(1000):
    data = generateData()
    w = linear_regression(data[0], data[1])
    X = np.insert(data[0], 0, values=1, axis=1)
    err += compute_linear_regression_error(X, data[1],w)
    if(i%100 == 0):
        print(i)
print(err/1000)    

0
100
200
300
400
500
600
700
800
900
0.5046430000000008


In [78]:
def transformX(X):
    Xprime = [[x[0], x[1], x[0]*x[1], x[0]*x[0], x[1]*x[1]] for x in X]
    return Xprime

In [80]:
def choiceBetweenW(w, X):
    X = np.insert(X, 0, values=1, axis=1)
    y_temp = np.dot(X,w)
    resultY = np.sign(y_temp)
    w1 = [-1, -1.5, 0.08, 0.13, 0.05, 0.05]
    w2 = [-1, -0.05, 0.08, 0.13, 1.5, 1.5]
    w3 = [-1, -0.05, 0.08, 0.13, 1.5, 15]
    w4 = [-1, -1.5, 0.08, 0.13, 0.05, 1.5]
    w5 = [-1, -0.05, 0.08, 0.13, 15, 1.5]
    
    wlist = []
    wlist.append(w1)
    wlist.append(w2)
    wlist.append(w3)
    wlist.append(w4)
    max_err = 0
    result = None
    for eachw in wlist:
        err = compute_linear_regression_error(X,resultY,eachw)
        if(err > max_err):
            max_err = err
            result = eachw
    return result
    

In [85]:
data = generateData()
xPrime = transformX(data[0])
w = linear_regression(xPrime, data[1])
w

matrix([[-0.99657457],
        [-0.06605464],
        [ 0.00901934],
        [ 0.03360177],
        [ 1.57036257],
        [ 1.53179721]])

In [86]:
wPrime = choiceBetweenW(w, xPrime)
wPrime

[-1, -1.5, 0.08, 0.13, 0.05, 0.05]

In [122]:
err = 0
for i in range(1000):
    data = generateData()
    Xprime = transformX(data[0])
    w = pocket(Xprime, data[1], 50)[0]
    testData = generateData()
    testX = np.insert(transformX(testData[0]), 0, values=1, axis=1)
    err += compute_error(w, testX, testData[1])
    if(i%100 == 0):
        print(i)
        print(err)
print(err/1000)

0
0.202
100
18.122999999999998
200
36.06899999999999
300
53.98999999999996
400
72.762
500
90.62399999999998
600
108.22199999999995
700
126.44899999999991
800
144.87699999999987
900
163.41300000000004
0.18113900000000005


In [8]:
def theta(x):
    return np.divide(1, 1+ np.exp(np.multiply(-1,x)))

In [146]:
def NewtonGradient(X,Y,w):
    temp = np.zeros(np.shape(X)[1])
    for i in range(len(X)):
        x = X[i]
        y = Y[i]
        temp = np.add(temp,np.multiply(theta(-1*y*np.dot(w,x)), np.multiply(-1*y, x)))
    return np.divide(temp, len(X))

In [10]:
def update(ita,w,gradient):
    return np.subtract(w, np.multiply(ita, gradient))

In [5]:
import pandas as pd

In [6]:
df_train = pd.read_csv("hw3_train.dat", delim_whitespace=True,header=None)
X_train = df_train.loc[:,:19].values
X_train = np.insert(X_train, 0, values=1, axis=1)
Y_train = df_train[20].values

In [177]:
def logistic(X, Y,ita,T):    
    d = np.shape(X)[1]
    N = np.shape(X)[0]
    w = np.zeros(d)
    for i in range(T):
        gradient = NewtonGradient(X,Y,w)
        if(gradient.sum() == 0):
            break
        w = update(ita,w,gradient)
    return w

In [186]:
w = logistic(X_train, Y_train, 0.001, 2000)

In [187]:
w

array([ 0.01878417, -0.01260595,  0.04084862, -0.03266317,  0.01502334,
       -0.03667437,  0.01255934,  0.04815065, -0.02206419,  0.02479605,
        0.06899284,  0.0193719 , -0.01988549, -0.0087049 ,  0.04605863,
        0.05793382,  0.061218  , -0.04720391,  0.06070375, -0.01610907,
       -0.03484607])

In [13]:
df_test = pd.read_csv("hw3_test.dat", delim_whitespace=True,header=None)
X_test = df_train.loc[:,:19].values
X_test = np.insert(X_test, 0, values=1, axis=1)
Y_test = df_train[20].values

In [14]:
def compute_error(X, Y, w):
    y_temp = theta(np.dot(X,w))
    y = np.zeros(len(y_temp))
    y[y_temp>0.5] = 1
    y[y_temp == 0.5] = 1
    y[y_temp<0.5] = -1
    count = 0
    for i in range(len(Y)):
        if(Y[i] != y[i]):
            count+=1
    return count/len(Y)

In [17]:
def randomGradient(X,Y,w,n):
    temp = np.zeros(np.shape(X)[1])
    for i in range(n):
        #randint = np.random.randint(len(X))
        x = X[i]
        y = Y[i]
        temp = np.add(temp,np.multiply(theta(-1*y*np.dot(w,x)), np.multiply(-1*y, x)))
    return np.divide(temp, n)

In [18]:
def logistic_random_gradient(X, Y,ita,T):    
    d = np.shape(X)[1]
    N = np.shape(X)[0]
    w = np.zeros(d)
    n = 0
    for i in range(T):
        n+=1
        if(n >= len(X)):
            n = 1
        gradient = randomGradient(X,Y,w,n)
        if(gradient.sum() == 0):
            break
        w = update(ita,w,gradient)
    return w

In [21]:
w = logistic_random_gradient(X_train, Y_train, 0.01, 2000)

In [22]:
compute_error(X_test, Y_test, w)

0.228